# Generated by Django 4.1.4 on 2024-08-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forklift', '0004_alter_repair_options_remove_repair_can_fix_brands_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forklift',
            name='hours_run',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
