# Generated by Django 4.1.4 on 2024-08-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forklift', '0005_alter_forklift_hours_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forklift',
            name='hours_run',
            field=models.FloatField(default=0),
        ),
    ]
