# Generated by Django 4.1.4 on 2024-08-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forklift', '0009_forklift_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='forklift',
            name='workshops',
            field=models.JSONField(default=list),
        ),
    ]
