# Generated by Django 4.1.4 on 2024-08-08 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forklift', '0010_forklift_workshops'),
    ]

    operations = [
        migrations.AddField(
            model_name='forklift',
            name='fastest_workshop',
            field=models.IntegerField(default=0),
        ),
    ]
